### ISSUE TITLE
Tratar BOM

### ISSUE THREAD

**Issue by DeeSouza** [osians/CSVLib#1]
Opa! Muito boa sua biblioteca!
Acho que seria interessante ter um tratamento para o BOM.
A primeira coluna do CSV está vindo com isso: ` i»¿`.

Então fica a dica da função:

`csv.class.php`

 ```
 /* Remove BOM PHP */
	public function removeBOM($text){
	    $bom 	= pack('H*','EFBBBF');
	    $text 	= preg_replace("/^$bom/", '', $text);
	    return $text;
	}
```

```
private function tratarIndices($str){
   $str = $this->removeBOM($str);
   .
   .
   .

```
Obrigado!

---

Eu sugeri a atualização porquê as vezes **não se sabe como o usuário monta o arquivo**. Eu fiquei penando aqui pra subir um arquivo, não reconhecia a primeira coluna. Daí abri no Sublime Text com codificação árabe, daí apareceu aqueles caracteres.

**Comment by osians** [comment]
Olá Diego, 
eu quem agradeço. Sua correção é muito bem vinda para melhorar o script. 
Já foi adicionada com os devidos reconhecimentos.
Obrigado!
